api: nx run api:serve
tasks: nx run tasks:serve
webapp: nx run webapp:serve
watcher: nx run watcher:serve
encoder: nx run encoder:serve
scheduler: nx run scheduler:serve
odm-downloader: nx run odm-downloader:serve
media-processor: nx run media-processor:serve
overdrive-retriever: nx run overdrive-retriever:serve
